### ISSUE TITLE
OAuthError: 400 during prepare OTP phase

### ISSUE THREAD

**Issue by sylvain-sicard** [lelas33/plugin_peugeotcars#30]
Since a couple of days an OAuth error occurs during psa daemon authentication.
It occurs while the setup was running whithout error since multiples months.
Both password & pin code are still valid (tested by sending commands to the car with the MyPeugeot android app).
I tried to reinstall the plugin and I tested the fork from @dricair, but still the same error.

Logs in the peugeotcars_otp :
Requested API level 33 is larger than maximum we have, returning API level 28 instead.
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
RES_TABLE_LIBRARY_TYPE chunk is not supported
400  - server_error : Internal Server Error
Traceback (most recent call last):
  File "/var/www/html/plugins/peugeotcars/core/ajax/../../3rdparty/psa_jeedom_daemon/jeedom_otp.py", line 69, in <module>
    res = firstLaunchConfig(pkg_name, mail, password, country)
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/psa/setup/app_decoder.py", line 94, in firstLaunchConfig
    psacc.connect(client_email, client_password)
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/psacc/application/psa_client.py", line 34, in connect
    self.manager.init_with_user_credentials_realm(user, password, self.realm)
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/psa/oauth.py", line 28, in init_with_user_credentials_realm
    self._token_request(self._grant_password_request_realm(login, password, realm), True)
  File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 205, in _token_request
    CredentialManager._handle_bad_response(response)
  File "/usr/local/lib/python3.9/dist-packages/oauth2_client/credentials_manager.py", line 87, in _handle_bad_response
    raise OAuthError(HTTPStatus(response.status_code), error.get('error'), error.get('error_description'))
oauth2_client.credentials_manager.OAuthError: 400  - server_error : Internal Server Error

**Comment by Anthony-55** [comment]
@lelas33, même problème pour moi, as tu des pistes ou besoin de tests supplémentaires ?

**Comment by sylvain-sicard** [comment]
Not sure if it helps to troubleshoot but I tried to upgrade the APK to 1.43.1 (from https://www.frandroid.com/telecharger/apps/mypeugeot-app-peugeot).
I still get the same error.

**Comment by domB54** [comment]
Bonjour,
Exactement le même problème, même log pour moi sur Jeedom Atlas version 4.3.22
Une idée ?
Merci

**Comment by sylvain-sicard** [comment]
Le sujet est évoqué ici : 
https://community.jeedom.com/t/plugin-peugeotcars-preparation-otp-impossible/119549/2

A priori peu d'espoir.....

**Comment by JeedHome44** [comment]
Bonjour,

Regardez du côté de PSA CAR sur Home assistant.

Il y a une issue qui donne une solution mais je n'ai pas compris comment l'appliquer 

https://github.com/flobz/psa_car_controller/issues/767
