### ISSUE TITLE
Can't get Otp code

### ISSUE THREAD

**Issue by TiphTech** [lelas33/plugin_peugeotcars#5]
Salut! Félicitation pour cette mise a jour qui à l'aire bien complète, par contre j'ai mis visiblement trop de temps à rentrer le code reçu par sms il ne doit plus être valide, comment faire pour en recevoir un nouveau?
Merci

2021-04-22 07:23:53,344 :: ERROR :: Renouvelez votre code OTP!!
Traceback (most recent call last):
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/MyPSACC.py", line 271, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/otp/Otp.py", line 274, in get_otp_code
    raise ConfigException("Can't get otp code")
otp.Otp.ConfigException: Can't get otp code

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/var/www/html/plugins/peugeotcars/core/class/../../3rdparty/psa_jeedom_daemon/jeedom_gateway.py", line 71, in <module>
    myp.start_mqtt()
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/MyPSACC.py", line 363, in start_mqtt
    self.refresh_remote_token()
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/MyPSACC.py", line 308, in refresh_remote_token
    otp_code = self.get_otp_code()
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/utils.py", line 37, in wrapper
    return fn(*args, **kwargs)
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/MyPSACC.py", line 274, in get_otp_code
    otp_code = self.otp.get_otp_code()
  File "/var/www/html/plugins/peugeotcars/3rdparty/psa_jeedom_daemon/psa_car_controller/otp/Otp.py", line 274, in get_otp_code
    raise ConfigException("Can't get otp code")
otp.Otp.ConfigException: Can't get otp code

**Comment by TiphTech** [comment]
Ah! C'est bon, en relançant les dépendances j'ai reçu un nouveau code que j'ai mis direct, c'est Ok

**Comment by lelas33** [comment]
C'est bien ce qu'il fallait faire. La requête pour l'envoi du SMS est faite à la fin de l'installation des dépendances.
Je vais le rajouter dans la doc.

**Comment by Roccoswell** [comment]
Bonjour,

Merci pour ce super plugin.

J'ai un problème similaire, j'ai tenté de désinstaller, re-installer le plugin, de suivre rigoureseument l'ordre des étapes, mais toujours ces messages :
2021-04-27 23:01:01,985 :: ERROR :: retry last request, token was expired
2021-04-27 23:01:30,604 :: INFO :: Token expired error detected => Resend last command
[2021-04-28 00:03:05][ERROR] : Erreur sur peugeotcars::pull() : [MySQL] Error code : 42S02 (1146). Table 'jeedom.object' doesn't exist  : SELECT `el`.`id`, `el`.`name`, `el`.`logicalId`, `el`.`generic_type`, `el`.`object_id`, `el`.`eqType_name`, `el`.`isVisible`, `el`.`isEnable`, `el`.`configuration`, `el`.`timeout`, `el`.`category`, `el`.`display`, `el`.`order`, `el`.`comment`, `el`.`tags` 		FROM eqLogic el 		LEFT JOIN object ob ON el.object_id=ob.id 		WHERE eqType_name=:eqType_name  ORDER BY ob.name,el.name

Je peux "lire" les info provenant de la peugeot, mais pas "envoyer" (commande charge ou clim)
